"""Generate recovered official attribute definitions from decoded bindict data."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


SOURCE_BASENAME = "06294_d88af3df.pyc"


def find_attribute_table(scan: dict[str, Any]) -> dict[str, Any]:
    for record in scan.get("files", []):
        if SOURCE_BASENAME in record.get("path", ""):
            parsed = record.get("parsed", {})
            data = parsed.get("data")
            if isinstance(data, dict):
                return data
    raise ValueError(f"Could not find {SOURCE_BASENAME} in scan JSON")


def emit_ts(table: dict[str, Any], source_scan: Path) -> str:
    rows = []
    for key, value in sorted(table.items(), key=lambda item: item[0].lower()):
        if not isinstance(value, dict):
            continue
        rows.append({
            "key": key,
            "attrId": value.get("attr_id", ""),
            "calcType": value.get("calc_type", 0),
            "entityType": value.get("ent_type", 0),
            "valueType": value.get("val_type", 0),
            "initialValue": value.get("init_val", 0),
            "minValue": value.get("min_val", 0),
            "maxValue": value.get("max_val", 0),
            "parentAttrKey": value.get("parent_attr_key", ""),
            "libraryNo": value.get("lib_no", 0),
        })

    body = json.dumps(rows, ensure_ascii=False, indent=2)
    return "\n".join([
        "// Generated by scripts/generate_recovered_attributes.py.",
        f"// Source: {SOURCE_BASENAME} from {source_scan}",
        "",
        "export interface RecoveredOfficialAttributeDefinition {",
        "  key: string;",
        "  attrId: string;",
        "  calcType: number;",
        "  entityType: number;",
        "  valueType: number;",
        "  initialValue: number;",
        "  minValue: number;",
        "  maxValue: number;",
        "  parentAttrKey: string;",
        "  libraryNo: number;",
        "}",
        "",
        f"export const RECOVERED_OFFICIAL_ATTRIBUTES = {body} as const satisfies readonly RecoveredOfficialAttributeDefinition[];",
        "",
        "export type RecoveredOfficialAttributeKey = typeof RECOVERED_OFFICIAL_ATTRIBUTES[number]['key'];",
        "",
        "export const RECOVERED_OFFICIAL_ATTRIBUTE_BY_KEY: ReadonlyMap<string, RecoveredOfficialAttributeDefinition> =",
        "  new Map(RECOVERED_OFFICIAL_ATTRIBUTES.map((attr) => [attr.key, attr]));",
        "",
        "export const RECOVERED_OFFICIAL_ATTRIBUTE_BY_ID: ReadonlyMap<string, RecoveredOfficialAttributeDefinition> =",
        "  new Map(RECOVERED_OFFICIAL_ATTRIBUTES.map((attr) => [attr.attrId, attr]));",
        "",
        "export function getRecoveredOfficialAttribute(key: string): RecoveredOfficialAttributeDefinition | undefined {",
        "  return RECOVERED_OFFICIAL_ATTRIBUTE_BY_KEY.get(key);",
        "}",
        "",
    ])


def main() -> int:
    cli = argparse.ArgumentParser(description="Generate official attribute definitions recovered from bindict scan output.")
    cli.add_argument("scan_json", help="Path to bindict_scan.json")
    cli.add_argument("-o", "--output", required=True, help="Output TypeScript file")
    args = cli.parse_args()

    source = Path(args.scan_json).resolve()
    scan = json.loads(source.read_text(encoding="utf-8"))
    table = find_attribute_table(scan)
    output = Path(args.output).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(emit_ts(table, source), encoding="utf-8")
    print(json.dumps({"attributeCount": len(table), "output": str(output)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
