import type { CanonicalArmor, CanonicalKeyGear } from "../itemTypes";
import { key_gear as generatedKeyGear } from "./generated/key-gear.generated";
import { effectSummaryToStatModifiers } from "../../utils/statKeyMapper";

export const armorRegistry: CanonicalArmor[] = [
 {
  id: "lonewolf-head",
  name: "Lone Wolf Hood",
  category: "armor",
  slot: "head",
  armorSet: "Lone Wolf",
  tags: ["set:lonewolf", "crit"],
  keywordAssociations: ["crit"],
  effectSummary: "Part of the Lone Wolf set. Crit and reload-focused build.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name verified.",
 },
 {
  id: "lonewolf-mask",
  name: "Lone Wolf Mask",
  category: "armor",
  slot: "mask",
  armorSet: "Lone Wolf",
  tags: ["set:lonewolf", "crit"],
  keywordAssociations: ["crit"],
  effectSummary: "Part of the Lone Wolf set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name verified.",
 },
 {
  id: "lonewolf-chest",
  name: "Lone Wolf Chest",
  category: "armor",
  slot: "chest",
  armorSet: "Lone Wolf",
  tags: ["set:lonewolf", "crit"],
  keywordAssociations: ["crit"],
  effectSummary: "Part of the Lone Wolf set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name verified.",
 },
 {
  id: "lonewolf-gloves",
  name: "Lone Wolf Gloves",
  category: "armor",
  slot: "gloves",
  armorSet: "Lone Wolf",
  tags: ["set:lonewolf", "crit"],
  keywordAssociations: ["crit"],
  effectSummary: "Part of the Lone Wolf set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name verified.",
 },
 {
  id: "lonewolf-pants",
  name: "Lone Wolf Pants",
  category: "armor",
  slot: "pants",
  armorSet: "Lone Wolf",
  tags: ["set:lonewolf", "crit"],
  keywordAssociations: ["crit"],
  effectSummary: "Part of the Lone Wolf set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name verified.",
 },
 {
  id: "lonewolf-boots",
  name: "Lone Wolf Boots",
  category: "armor",
  slot: "boots",
  armorSet: "Lone Wolf",
  tags: ["set:lonewolf", "crit"],
  keywordAssociations: ["crit"],
  effectSummary: "Part of the Lone Wolf set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name verified.",
 },
 {
  id: "shelterer-head",
  name: "Shelterer Hood",
  category: "armor",
  slot: "head",
  armorSet: "Shelterer",
  tags: ["set:shelterer", "elemental"],
  keywordAssociations: ["elemental"],
  effectSummary: "Part of the Shelterer set. Elemental-oriented armor.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name verified.",
 },
 {
  id: "shelterer-mask",
  name: "Shelterer Mask",
  category: "armor",
  slot: "mask",
  armorSet: "Shelterer",
  tags: ["set:shelterer", "elemental"],
  keywordAssociations: ["elemental"],
  effectSummary: "Part of the Shelterer set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name verified.",
 },
 {
  id: "shelterer-chest",
  name: "Shelterer Chest",
  category: "armor",
  slot: "chest",
  armorSet: "Shelterer",
  tags: ["set:shelterer", "elemental"],
  keywordAssociations: ["elemental"],
  effectSummary: "Part of the Shelterer set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name verified.",
 },
 {
  id: "shelterer-gloves",
  name: "Shelterer Gloves",
  category: "armor",
  slot: "gloves",
  armorSet: "Shelterer",
  tags: ["set:shelterer", "elemental"],
  keywordAssociations: ["elemental"],
  effectSummary: "Part of the Shelterer set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name verified.",
 },
 {
  id: "shelterer-pants",
  name: "Shelterer Pants",
  category: "armor",
  slot: "pants",
  armorSet: "Shelterer",
  tags: ["set:shelterer", "elemental"],
  keywordAssociations: ["elemental"],
  effectSummary: "Part of the Shelterer set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name verified.",
 },
 {
  id: "shelterer-boots",
  name: "Shelterer Boots",
  category: "armor",
  slot: "boots",
  armorSet: "Shelterer",
  tags: ["set:shelterer", "elemental"],
  keywordAssociations: ["elemental"],
  effectSummary: "Part of the Shelterer set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name verified.",
 },
 {
  id: "blackstone-head",
  name: "Blackstone Hood",
  category: "armor",
  slot: "head",
  armorSet: "Blackstone",
  tags: ["set:blackstone", "resist"],
  keywordAssociations: [],
  effectSummary: "Part of the Blackstone set. Temperature and resistance interactions.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "blackstone-mask",
  name: "Blackstone Mask",
  category: "armor",
  slot: "mask",
  armorSet: "Blackstone",
  tags: ["set:blackstone", "resist"],
  keywordAssociations: [],
  effectSummary: "Part of the Blackstone set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "blackstone-chest",
  name: "Blackstone Chest",
  category: "armor",
  slot: "chest",
  armorSet: "Blackstone",
  tags: ["set:blackstone", "resist"],
  keywordAssociations: [],
  effectSummary: "Part of the Blackstone set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "blackstone-gloves",
  name: "Blackstone Gloves",
  category: "armor",
  slot: "gloves",
  armorSet: "Blackstone",
  tags: ["set:blackstone", "resist"],
  keywordAssociations: [],
  effectSummary: "Part of the Blackstone set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "blackstone-pants",
  name: "Blackstone Pants",
  category: "armor",
  slot: "pants",
  armorSet: "Blackstone",
  tags: ["set:blackstone", "resist"],
  keywordAssociations: [],
  effectSummary: "Part of the Blackstone set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "blackstone-boots",
  name: "Blackstone Boots",
  category: "armor",
  slot: "boots",
  armorSet: "Blackstone",
  tags: ["set:blackstone", "resist"],
  keywordAssociations: [],
  effectSummary: "Part of the Blackstone set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "renegade-head",
  name: "Renegade Hood",
  category: "armor",
  slot: "head",
  armorSet: "Renegade",
  tags: ["set:renegade", "weapon-dmg", "precision"],
  keywordAssociations: ["weakspot"],
  effectSummary: "Part of the Renegade set. Weapon damage and precision-facing.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "renegade-mask",
  name: "Renegade Mask",
  category: "armor",
  slot: "mask",
  armorSet: "Renegade",
  tags: ["set:renegade", "weapon-dmg", "precision"],
  keywordAssociations: ["weakspot"],
  effectSummary: "Part of the Renegade set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "renegade-chest",
  name: "Renegade Chest",
  category: "armor",
  slot: "chest",
  armorSet: "Renegade",
  tags: ["set:renegade", "weapon-dmg", "precision"],
  keywordAssociations: ["weakspot"],
  effectSummary: "Part of the Renegade set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "renegade-gloves",
  name: "Renegade Gloves",
  category: "armor",
  slot: "gloves",
  armorSet: "Renegade",
  tags: ["set:renegade", "weapon-dmg", "precision"],
  keywordAssociations: ["weakspot"],
  effectSummary: "Part of the Renegade set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "renegade-pants",
  name: "Renegade Pants",
  category: "armor",
  slot: "pants",
  armorSet: "Renegade",
  tags: ["set:renegade", "weapon-dmg", "precision"],
  keywordAssociations: ["weakspot"],
  effectSummary: "Part of the Renegade set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "renegade-boots",
  name: "Renegade Boots",
  category: "armor",
  slot: "boots",
  armorSet: "Renegade",
  tags: ["set:renegade", "weapon-dmg", "precision"],
  keywordAssociations: ["weakspot"],
  effectSummary: "Part of the Renegade set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "bastille-head",
  name: "Bastille Hood",
  category: "armor",
  slot: "head",
  armorSet: "Bastille",
  tags: ["set:bastille", "defensive"],
  keywordAssociations: [],
  effectSummary: "Part of the Bastille set. Defensive armor option.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "bastille-mask",
  name: "Bastille Mask",
  category: "armor",
  slot: "mask",
  armorSet: "Bastille",
  tags: ["set:bastille", "defensive"],
  keywordAssociations: [],
  effectSummary: "Part of the Bastille set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "bastille-chest",
  name: "Bastille Chest",
  category: "armor",
  slot: "chest",
  armorSet: "Bastille",
  tags: ["set:bastille", "defensive"],
  keywordAssociations: [],
  effectSummary: "Part of the Bastille set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "bastille-gloves",
  name: "Bastille Gloves",
  category: "armor",
  slot: "gloves",
  armorSet: "Bastille",
  tags: ["set:bastille", "defensive"],
  keywordAssociations: [],
  effectSummary: "Part of the Bastille set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "bastille-pants",
  name: "Bastille Pants",
  category: "armor",
  slot: "pants",
  armorSet: "Bastille",
  tags: ["set:bastille", "defensive"],
  keywordAssociations: [],
  effectSummary: "Part of the Bastille set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
 {
  id: "bastille-boots",
  name: "Bastille Boots",
  category: "armor",
  slot: "boots",
  armorSet: "Bastille",
  tags: ["set:bastille", "defensive"],
  keywordAssociations: [],
  effectSummary: "Part of the Bastille set.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Set name from catalog.",
 },
];

export const keyGearRegistry: CanonicalKeyGear[] = [
 ...generatedKeyGear.map((k) => {
  if (k.statModifiers && k.statModifiers.length > 0) return k;
  const parsed = effectSummaryToStatModifiers(k.effectSummary ?? "");
  if (parsed.length === 0) return k;
  return { ...k, statModifiers: parsed };
 }),
 {
  id: "manual-blue-flame-boots",
  name: "Blue Flame Boots",
  category: "key_gear",
  slot: "boots",
  tags: ["key-gear", "burn", "resistance-debuff", "manual"],
  keywordAssociations: ["burn"],
  effectSummary: "Applies Burn Resistance debuff to enemies on hit. Reduces enemy burn resistance per stack.",
  statModifiers: [],
  confidence: "estimated",
  needsReview: true,
  sourceNotes: "Manually curated, not in verified community sheet. Exact debuff values pending confirmation.",
  affectedMechanics: ["burn"],
 },
 {
  id: "manual-frost-whisper-boots",
  name: "Frost Whisper Boots",
  category: "key_gear",
  slot: "boots",
  tags: ["key-gear", "frost", "manual"],
  keywordAssociations: ["frostVortex"],
  effectSummary: "Enhances Frost Vortex mechanics. Details pending confirmation.",
  statModifiers: [],
  confidence: "experimental",
  needsReview: true,
  sourceNotes: "Manually curated, not in verified community sheet. Name from external reference.",
  affectedMechanics: ["frostVortex"],
 },
];

export function getArmor(id: string): CanonicalArmor | undefined {
 return armorRegistry.find((a) => a.id === id);
}

export function getArmorById(id: string): CanonicalArmor | undefined {
 return armorRegistry.find((a) => a.id === id);
}

export function getKeyGear(id: string): CanonicalKeyGear | undefined {
 return keyGearRegistry.find((k) => k.id === id);
}

export function listArmorSets(): string[] {
 return [...new Set(armorRegistry.map((a) => a.armorSet).filter(Boolean) as string[])];
}

export function getArmorBySlot(slot: string): CanonicalArmor[] {
 return armorRegistry.filter((a) => a.slot === slot);
}
