import type { CanonicalCradlePerk } from "../itemTypes";

export const cradleRegistry: CanonicalCradlePerk[] = [
 {
  id: "light-weapon-mastery",
  name: "Light Weapon Mastery",
  category: "cradle_perk",
  perkType: "weapon",
  tags: ["cradle", "weapon-mastery", "light-weapon", "weapon-class"],
  effectSummary: "Weapon DMG +15% while using Light Weapon class weapons (pistols, SMGs).",
  statModifiers: [{ stat: "weaponDMGBonus", value: 0.15, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Verified tooltip: 'Weapon DMG +15%' conditional on light weapon class.",
  maxLevel: 1,
  unlockGroup: "weapon-mastery",
  rowGroup: "weapon-mastery-row1",
  displayOrder: 1,
  effectType: "statBuff",
  formulaCandidateStats: ["weaponDMGBonus"],
  weaponClassTags: ["pistol", "smg"],
 },
 {
  id: "heavy-weapon-mastery",
  name: "Heavy Weapon Mastery",
  category: "cradle_perk",
  perkType: "weapon",
  tags: ["cradle", "weapon-mastery", "heavy-weapon", "weapon-class"],
  effectSummary: "Weapon DMG +15% while using Heavy Weapon class weapons (LMGs, shotguns).",
  statModifiers: [{ stat: "weaponDMGBonus", value: 0.15, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Verified tooltip: 'Weapon DMG +15%' conditional on heavy weapon class.",
  maxLevel: 1,
  unlockGroup: "weapon-mastery",
  rowGroup: "weapon-mastery-row1",
  displayOrder: 2,
  effectType: "statBuff",
  formulaCandidateStats: ["weaponDMGBonus"],
  weaponClassTags: ["lmg", "shotgun"],
 },
 {
  id: "precision-weapon-mastery",
  name: "Precision Weapon Mastery",
  category: "cradle_perk",
  perkType: "weapon",
  tags: ["cradle", "weapon-mastery", "precision-weapon", "weapon-class"],
  effectSummary: "Weapon DMG +15% while using Precision Weapon class weapons (rifles, snipers, crossbows).",
  statModifiers: [{ stat: "weaponDMGBonus", value: 0.15, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Verified tooltip: 'Weapon DMG +15%' conditional on precision weapon class.",
  maxLevel: 1,
  unlockGroup: "weapon-mastery",
  rowGroup: "weapon-mastery-row1",
  displayOrder: 3,
  effectType: "statBuff",
  formulaCandidateStats: ["weaponDMGBonus"],
  weaponClassTags: ["rifle", "sniper", "crossbow"],
 },
 {
  id: "tactical-combo",
  name: "Tactical Combo",
  category: "cradle_perk",
  perkType: "combat",
  tags: ["cradle", "combo", "reload", "weapon-swap"],
  effectSummary: "Weapon DMG +15% for 4s after weapon swap or reload.",
  statModifiers: [{ stat: "weaponDMGBonus", value: 0.15, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. 4s window confirmed. Conditional on reload/swap trigger.",
  maxLevel: 1,
  unlockGroup: "special",
  rowGroup: "special-row1",
  displayOrder: 4,
  effectType: "conditionalBuff",
  formulaCandidateStats: ["weaponDMGBonus"],
  unresolvedMechanics: ["4s buff window not modeled — uptime estimated from reload frequency. Does not differentiate weapon-swap vs reload trigger."],
 },
 {
  id: "status-enhancement",
  name: "Status Enhancement",
  category: "cradle_perk",
  perkType: "status",
  tags: ["cradle", "status", "weakspot", "uptime"],
  effectSummary: "Status DMG +15% for 3s after weakspot hit.",
  statModifiers: [{ stat: "statusDMGBonus", value: 0.15, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. 3s window after weakspot confirmed.",
  maxLevel: 1,
  unlockGroup: "status-elemental",
  rowGroup: "status-row1",
  displayOrder: 5,
  effectType: "conditionalBuff",
  formulaCandidateStats: ["statusDMGBonus"],
  unresolvedMechanics: ["3s buff window not modeled — uptime estimated from weakspot accuracy assumptions."],
 },
 {
  id: "deadly-combo",
  name: "Deadly Combo",
  category: "cradle_perk",
  perkType: "combat",
  tags: ["cradle", "bounce", "shrapnel", "bullet-effect"],
  effectSummary: "Bullet effect DMG +25% for 4s after Bounce or Shrapnel trigger.",
  statModifiers: [{ stat: "bounceDMGBonus", value: 0.25, unit: "percent" }, { stat: "shrapnelDMGBonus", value: 0.25, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Bounce and Shrapnel mechanics pending formula implementation.",
  maxLevel: 1,
  unlockGroup: "special",
  rowGroup: "special-row2",
  displayOrder: 6,
  effectType: "conditionalBuff",
  formulaCandidateStats: ["bounceDMGBonus", "shrapnelDMGBonus"],
  unresolvedMechanics: ["4s buff window not modeled. Bounce and Shrapnel mechanics are pending — no proc rate available."],
 },
 {
  id: "elemental-sense",
  name: "Elemental Sense",
  category: "cradle_perk",
  perkType: "status",
  tags: ["cradle", "elemental", "status", "uptime"],
  effectSummary: "Elemental DMG +25% for 4s after dealing Elemental DMG.",
  statModifiers: [{ stat: "elementalDMGBonus", value: 0.25, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. 4s window after elemental damage confirmed.",
  maxLevel: 1,
  unlockGroup: "status-elemental",
  rowGroup: "status-row2",
  displayOrder: 7,
  effectType: "conditionalBuff",
  formulaCandidateStats: ["elementalDMGBonus"],
  unresolvedMechanics: ["4s buff window not modeled — uptime estimated from elemental trigger frequency. 'Corresponding element' selection not differentiated."],
 },
 {
  id: "steady-hand",
  name: "Steady Hand",
  category: "cradle_perk",
  perkType: "weapon",
  tags: ["cradle", "fortress-warfare", "fast-gunner", "weakspot", "weapon-dmg"],
  effectSummary: "Weapon DMG +10% and Weakspot DMG +25% while Fortress Warfare or Fast Gunner is active.",
  statModifiers: [{ stat: "weaponDMGBonus", value: 0.10, unit: "percent" }, { stat: "weakspotDMG", value: 0.25, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Conditional on Fortress Warfare or Fast Gunner uptime.",
  maxLevel: 1,
  unlockGroup: "special",
  rowGroup: "special-row2",
  displayOrder: 8,
  effectType: "conditionalBuff",
  formulaCandidateStats: ["weaponDMGBonus", "weakspotDMG"],
  unresolvedMechanics: ["Conditional on Fortress Warfare and Fast Gunner uptime. Both mechanics are pending."],
 },
 {
  id: "marked-strike",
  name: "Marked Strike",
  category: "cradle_perk",
  perkType: "combat",
  tags: ["cradle", "bullseye", "weakspot", "mark"],
  effectSummary: "Weakspot DMG +20% against Bull's Eye marked targets.",
  statModifiers: [{ stat: "weakspotDMG", value: 0.20, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Conditional on Bull's Eye mark being applied.",
  maxLevel: 1,
  unlockGroup: "offense",
  rowGroup: "offense-row2",
  displayOrder: 9,
  effectType: "conditionalBuff",
  formulaCandidateStats: ["weakspotDMG"],
  unresolvedMechanics: ["Conditional on Bull's Eye mark. Bull's Eye mechanic is pending."],
 },
 {
  id: "resilience",
  name: "Resilience",
  category: "cradle_perk",
  perkType: "survival",
  tags: ["cradle", "defensive", "shield", "pve"],
  effectSummary: "Shield damage reduction vs monsters only. No impact on outgoing DPS.",
  statModifiers: [],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. PvE-only defensive effect.",
  maxLevel: 1,
  unlockGroup: "defense-support",
  rowGroup: "defense-row1",
  displayOrder: 10,
  effectType: "defensive",
  formulaCandidateStats: [],
 },
 {
  id: "rapid-aid",
  name: "Rapid Aid",
  category: "cradle_perk",
  perkType: "survival",
  tags: ["cradle", "healing", "medicine", "utility"],
  effectSummary: "Medicine speed and effect utility perk. No direct damage impact.",
  statModifiers: [],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Healing/medicine utility only.",
  maxLevel: 1,
  unlockGroup: "defense-support",
  rowGroup: "defense-row1",
  displayOrder: 11,
  effectType: "utility",
  formulaCandidateStats: [],
 },
 {
  id: "deviant-energy-defense",
  name: "Deviant Energy Defense",
  category: "cradle_perk",
  perkType: "survival",
  tags: ["cradle", "defensive", "shield", "pvp", "mitigation"],
  effectSummary: "PvP defensive perk. Weapon/Status DMG Reduction +10% while shield is active. Shield grant + 30s duration + 30s CD.",
  statModifiers: [{ stat: "weaponDMGReduction", value: 0.10, unit: "percent" }, { stat: "statusDMGReduction", value: 0.10, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. PvP mitigation conditional on shield uptime.",
  maxLevel: 1,
  unlockGroup: "defense-support",
  rowGroup: "defense-row2",
  displayOrder: 12,
  effectType: "defensive",
  formulaCandidateStats: ["weaponDMGReduction", "statusDMGReduction"],
  unresolvedMechanics: ["Shield uptime and 30s cooldown not tracked. Damage reduction conditional on shield being active."],
 },
 {
  id: "shield-protection",
  name: "Shield Protection",
  category: "cradle_perk",
  perkType: "survival",
  tags: ["cradle", "defensive", "shield", "deviant-dmg"],
  effectSummary: "Deviant DMG Reduction and monster damage conditional on shield > 40% HP.",
  statModifiers: [],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. PvE/monster defensive conditional on shield threshold.",
  maxLevel: 1,
  unlockGroup: "defense-support",
  rowGroup: "defense-row2",
  displayOrder: 13,
  effectType: "defensive",
  formulaCandidateStats: ["deviantDMGReduction"],
  unresolvedMechanics: ["Shield conditionals not modeled. PvE monster damage bonus not in formula engine."],
 },
 {
  id: "energy-surge",
  name: "Energy Surge",
  category: "cradle_perk",
  perkType: "deviant",
  tags: ["cradle", "deviant", "power-recovery", "night"],
  effectSummary: "Deviant power recovery at night. No impact on outgoing DPS.",
  statModifiers: [],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Utility only — no combat formula impact.",
  maxLevel: 1,
  unlockGroup: "special",
  rowGroup: "special-row4",
  displayOrder: 14,
  effectType: "utility",
  formulaCandidateStats: [],
 },
 {
  id: "bounty-hunter",
  name: "Bounty Hunter",
  category: "cradle_perk",
  perkType: "combat",
  tags: ["cradle", "mark", "stacking", "weapon-dmg", "attack"],
  effectSummary: "First mark: Attack +2% per stack (max 5). Renew mark: Weapon DMG +3% per stack (max 5). Removed on weapon swap.",
  statModifiers: [{ stat: "attackPercent", value: 0.02, unit: "percent" }, { stat: "weaponDMGBonus", value: 0.03, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Two separate buff tracks with weapon-swap removal.",
  maxLevel: 1,
  unlockGroup: "offense",
  rowGroup: "offense-row2",
  displayOrder: 15,
  effectType: "stackingBuff",
  formulaCandidateStats: ["attackPercent", "weaponDMGBonus"],
  unresolvedMechanics: ["Two separate buff tracks not differentiated. Stacking not modeled. Weapon-swap removal not tracked."],
 },
 {
  id: "robust",
  name: "Robust",
  category: "cradle_perk",
  perkType: "combat",
  tags: ["cradle", "melee", "stacking", "weapon-dmg"],
  effectSummary: "Melee damage stacking perk. Weapon DMG increases with melee hits.",
  statModifiers: [],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Melee damage formula not yet modeled.",
  maxLevel: 1,
  unlockGroup: "melee",
  rowGroup: "melee-row1",
  displayOrder: 16,
  effectType: "stackingBuff",
  formulaCandidateStats: ["meleeDMGBonus"],
  unresolvedMechanics: ["Melee damage formula not modeled. Light vs heavy strike differentiation not tracked."],
 },
 {
  id: "extreme-freezing",
  name: "Extreme Freezing",
  category: "cradle_perk",
  perkType: "status",
  tags: ["cradle", "frost", "stacking", "frost-vortex", "slow", "freeze"],
  effectSummary: "Frost Vortex DMG +2.5% per stack (max 10) on Frost Elemental DMG. Slowdown and freeze CC effects.",
  statModifiers: [{ stat: "frostVortexDMGBonus", value: 0.025, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Stacking frost damage bonus on elemental trigger.",
  maxLevel: 1,
  unlockGroup: "status-elemental",
  rowGroup: "status-row2",
  displayOrder: 17,
  effectType: "stackingBuff",
  formulaCandidateStats: ["frostVortexDMGBonus"],
  unresolvedMechanics: ["Stacking decay not modeled. Freeze/slowdown CC not modeled. 1x freeze per target limit not tracked."],
 },
 {
  id: "blazing-detonation",
  name: "Blazing Detonation",
  category: "cradle_perk",
  perkType: "status",
  tags: ["cradle", "burn", "proc", "cooldown"],
  effectSummary: "Burn DMG +25% for 10s after re-inflicting Burn on a burning target. 3s cooldown.",
  statModifiers: [{ stat: "burnDMGBonus", value: 0.25, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Conditional on re-inflict with 3s internal cooldown.",
  maxLevel: 1,
  unlockGroup: "status-elemental",
  rowGroup: "status-row3",
  displayOrder: 18,
  effectType: "conditionalBuff",
  formulaCandidateStats: ["burnDMGBonus"],
  unresolvedMechanics: ["Re-inflict proc trigger not modeled. 3s cooldown not tracked. Extra Burn DMG instance not modeled."],
 },
 {
  id: "invincible-strike",
  name: "Invincible Strike",
  category: "cradle_perk",
  perkType: "combat",
  tags: ["cradle", "shrapnel", "stacking", "crit", "weakspot"],
  effectSummary: "Shrapnel DMG +2.5% and Shrapnel Crit DMG +3.5% per stack (max 10) on weakspot hit. 6s duration.",
  statModifiers: [{ stat: "shrapnelDMGBonus", value: 0.025, unit: "percent" }, { stat: "shrapnelCritDMGBonus", value: 0.035, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Weakspot-triggered shrapnel stacking.",
  maxLevel: 1,
  unlockGroup: "offense",
  rowGroup: "offense-row2",
  displayOrder: 19,
  effectType: "stackingBuff",
  formulaCandidateStats: ["shrapnelDMGBonus", "shrapnelCritDMGBonus"],
  unresolvedMechanics: ["Shrapnel mechanic is pending. Distance falloff removal at max stacks not tracked."],
 },
 {
  id: "bounce-rampage",
  name: "Bounce Rampage",
  category: "cradle_perk",
  perkType: "combat",
  tags: ["cradle", "bounce", "stacking", "bounce-dmg"],
  effectSummary: "Bounce DMG +5% per stack (max 5) on Bounce trigger. 15s duration.",
  statModifiers: [{ stat: "bounceDMGBonus", value: 0.05, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Bounce-triggered stacking buff.",
  maxLevel: 1,
  unlockGroup: "offense",
  rowGroup: "offense-row3",
  displayOrder: 20,
  effectType: "stackingBuff",
  formulaCandidateStats: ["bounceDMGBonus"],
  unresolvedMechanics: ["Bounce mechanic is pending — no proc rate available. Stacking decay not modeled."],
 },
 {
  id: "explosives-bonus",
  name: "Explosives Bonus",
  category: "cradle_perk",
  perkType: "status",
  tags: ["cradle", "unstable-bomber", "stacking", "explosion"],
  effectSummary: "Unstable Bomber DMG +5% per stack (max 5) on Unstable Bomber trigger. 8s duration.",
  statModifiers: [{ stat: "unstableBomberDMGBonus", value: 0.05, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Unstable Bomber stacking buff.",
  maxLevel: 1,
  unlockGroup: "status-elemental",
  rowGroup: "status-row3",
  displayOrder: 21,
  effectType: "stackingBuff",
  formulaCandidateStats: ["unstableBomberDMGBonus"],
  unresolvedMechanics: ["Stacking not modeled. 8s duration not tracked."],
 },
 {
  id: "heavy-strike",
  name: "Heavy Strike",
  category: "cradle_perk",
  perkType: "weapon",
  tags: ["cradle", "fortress-warfare", "weapon-dmg", "burst"],
  effectSummary: "Weapon DMG +25% for 8s after Fortress Warfare activation. Removed on weapon swap.",
  statModifiers: [{ stat: "weaponDMGBonus", value: 0.25, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Conditional on Fortress Warfare with weapon-swap removal.",
  maxLevel: 1,
  unlockGroup: "special",
  rowGroup: "special-row2",
  displayOrder: 22,
  effectType: "conditionalBuff",
  formulaCandidateStats: ["weaponDMGBonus"],
  unresolvedMechanics: ["Fortress Warfare mechanic is pending. Weapon-swap removal not tracked."],
 },
 {
  id: "transient-impact",
  name: "Transient Impact",
  category: "cradle_perk",
  perkType: "status",
  tags: ["cradle", "power-surge", "stacking", "surge-dmg"],
  effectSummary: "Power Surge DMG +2.5% per stack (max 10) on Power Surge DMG dealt. 6s duration.",
  statModifiers: [{ stat: "powerSurgeDMGBonus", value: 0.025, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Power Surge stacking buff.",
  maxLevel: 1,
  unlockGroup: "status-elemental",
  rowGroup: "status-row3",
  displayOrder: 23,
  effectType: "stackingBuff",
  formulaCandidateStats: ["powerSurgeDMGBonus"],
  unresolvedMechanics: ["Stacking decay not modeled. Power Surge model conflict (DoT vs hybrid) affects trigger frequency estimate."],
 },
 {
  id: "fast-pursuit",
  name: "Fast Pursuit",
  category: "cradle_perk",
  perkType: "combat",
  tags: ["cradle", "fast-gunner", "proc", "random", "stacking"],
  effectSummary: "Random effect on Fast Gunner trigger: Attack/Crit Rate/Crit DMG per stack (max 5). Removed on weapon swap.",
  statModifiers: [{ stat: "attackPercent", value: 0.02, unit: "percent" }, { stat: "critRate", value: 0.02, unit: "percent" }, { stat: "critDMG", value: 0.02, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Random selection between three buff types on Fast Gunner trigger.",
  maxLevel: 1,
  unlockGroup: "special",
  rowGroup: "special-row3",
  displayOrder: 24,
  effectType: "stackingBuff",
  formulaCandidateStats: ["attackPercent", "critRate", "critDMG"],
  unresolvedMechanics: ["Random effect selection not modeled — contribution shown is average of three possibilities. Fast Gunner mechanic is pending. Weapon-swap removal not tracked."],
 },
 {
  id: "brawl-boost",
  name: "Brawl Boost",
  category: "cradle_perk",
  perkType: "survival",
  tags: ["cradle", "melee", "defensive", "stacking", "dmg-reduction"],
  effectSummary: "Damage Reduction +5% per stack (max 5) after dealing melee damage. Removed on weapon swap.",
  statModifiers: [{ stat: "playerDMGReduction", value: 0.05, unit: "percent" }],
  confidence: "observed",
  needsReview: false,
  sourceNotes: "Extracted from user-provided in-game hover footage. Melee-triggered defensive stacking with weapon-swap removal.",
  maxLevel: 1,
  unlockGroup: "defense-support",
  rowGroup: "defense-row3",
  displayOrder: 25,
  effectType: "stackingBuff",
  formulaCandidateStats: ["playerDMGReduction"],
  unresolvedMechanics: ["Melee trigger not modeled. Stacking not modeled. Weapon-swap removal not tracked."],
 },
];

export function getCradlePerk(id: string): CanonicalCradlePerk | undefined {
 return cradleRegistry.find((p) => p.id === id);
}

export function listCradlePerkTypes(): string[] {
 return [...new Set(cradleRegistry.map((p) => p.perkType))];
}
